# Generated by Django 3.2.6 on 2021-08-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files', verbose_name='Uploaded file')),
            ],
            options={
                'verbose_name': 'Excel File',
                'verbose_name_plural': 'Excel Files',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=60, verbose_name='Column name')),
                ('summary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summary value')),
                ('average', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Average value')),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.excelfile', verbose_name='Excel File')),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
            },
        ),
    ]
